### ISSUE TITLE
More options for rendering stylesheets

### ISSUE THREAD

**Issue by onionhammer** [madskristensen/ImageSprites#9]
It would be great if instead of generating something like this:

```less
.ats-state-12() {
	width: 80px;
	height: 98px;
	display: inline-block;
	background: url('ats-state.sprite.png') -991px -2px no-repeat;
}
.ats-state-13() {
	width: 80px;
	height: 98px;
	display: inline-block;
	background: url('ats-state.sprite.png') -1073px -2px no-repeat;
}
```

it would generate something like this

```less
.ats-state() {
	background-image: url('ats-state.sprite.png');
        background-repeat: no-repeat;
}
.ats-state-12() {
	background-position: -991px -2px;
}
.ats-state-13() {
	background-position: -1073px -2px;
}
```

Just to make the functions more composable when working with them
